CycleCollectors: N
	Description: hotkey-description-cyclecollectors
	Types: World
	Contexts: player, spectator

ProductionTypeGeneralsPower: G
	Description: hotkey-description-productiontypegeneralspower
	Types: Production
	Contexts: player

ProductionScrollUp: O
	Description: hotkey-description-productionscollup
	Types: Production
	Contexts: player

ProductionScrollDown: L
	Description: hotkey-description-productionscolldown
	Types: Production
	Contexts: player

StatisticsMinimal: BACKQUOTE
	Description: hotkey-description-statisticminimal
	Types: Observer
	Contexts: spectator

StatisticsUpgrades: F8
	Description: hotkey-description-statisticupgrades
	Types: Observer
	Contexts: spectator
