name: Continuous Integration

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  linux:
    name: Linux (.NET 8.0)
    runs-on: ubuntu-22.04

    steps:
      - name: Remove System .NET
        run: sudo apt-get remove -y dotnet*

      - name: Clone Repository
        uses: actions/checkout@v5

      - name: Install .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Prepare Environment
        run: |
          . mod.config;
          awk '/\r$$/ { exit(1); }' mod.config || (printf "Invalid mod.config format. File must be saved using unix-style (LF, not CRLF or CR) line endings.\n"; exit 1);

      - name: Check Code
        run: |
          make check
          make check-packaging-scripts

      - name: Check Mod
        run: |
          sudo apt-get install lua5.1
          make check-scripts
          make test

  windows:
    name: Windows (.NET 8.0)
    runs-on: windows-2022

    steps:
      - name: Clone Repository
        uses: actions/checkout@v5

      - name: Install .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Check Code
        shell: powershell
        run: |
          # Work around runtime failures on the GH Actions runner
          dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
          .\make.ps1 check

      - name: Check Mods
        run: |
          choco install lua --version 5.1.5.52 --no-progress
          $ENV:Path = $ENV:Path + ";C:\Program Files (x86)\Lua\5.1\"
          .\make.ps1 check-scripts
          .\make.ps1 test
